<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Articles.aspx.cs" Inherits="Kawanoikioi.Admin.Articles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="ArticlesAdminView" runat="server" AutoGenerateColumns="False" 
        DataSourceID="ObjectDataSource1" AllowPaging="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="UniqueName" HeaderText="UniqueName" 
                SortExpression="UniqueName" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Content" HeaderText="Content" 
                SortExpression="Content" />
            <asp:BoundField DataField="Author" HeaderText="Author" 
                SortExpression="Author" />
            <asp:CheckBoxField DataField="IsPublished" HeaderText="IsPublished" 
                SortExpression="IsPublished" />
            <asp:BoundField DataField="SubmissionDate" HeaderText="SubmissionDate" 
                SortExpression="SubmissionDate" />
            <asp:BoundField DataField="LastModified" HeaderText="LastModified" 
                SortExpression="LastModified" />
        </Columns>
    </asp:GridView>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
        SelectMethod="GetAllArticles" TypeName="Kawanoikioi.Models.AdminRepository">
    </asp:ObjectDataSource>
</asp:Content>
