<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true"
    CodeBehind="Forums.aspx.cs" Inherits="Kawanoikioi.Admin.Forums" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <ajaxToolkit:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
    </ajaxToolkit:ToolkitScriptManager>
    <br />
    <asp:Label ID="ForumsAdminHeader" runat="server" Text="Forums Administration"></asp:Label>
    <br />
    <asp:GridView ID="ForumAdminView" runat="server" AutoGenerateColumns="False" DataSourceID="ObjectDataSource1"
        AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="UniqueName" HeaderText="UniqueName" SortExpression="UniqueName" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" SortExpression="CategoryID" />
            <asp:BoundField DataField="OrderID" HeaderText="OrderID" SortExpression="OrderID" />
        </Columns>
    </asp:GridView>
    <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="GetForums"
        TypeName="Kawanoikioi.Models.AdminRepository"></asp:ObjectDataSource>
    <asp:Panel ID="AddForumPanel" runat="server">
        <asp:Label ID="AddForumHeader" runat="server" Text="Create a new forum."></asp:Label>
        <br />
        <asp:Label ID="NameLabel" runat="server" Text="Name:"></asp:Label>
        &nbsp;&nbsp;&nbsp;
        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="NameTextBox"
            ErrorMessage="A name for the forum must be specified."></asp:RequiredFieldValidator>
        <br />
        <asp:TextBox ID="NameTextBox" runat="server"></asp:TextBox>
        <br />
        <asp:Label ID="CategoryLabel" runat="server" Text="Please select a category to host the forum below:"></asp:Label>
        <br />
        <asp:DropDownList ID="CategoryList" runat="server" DataSourceID="ObjectDataSource2"
            DataTextField="Name" DataValueField="ID">
        </asp:DropDownList>
        <asp:ObjectDataSource ID="ObjectDataSource2" runat="server" SelectMethod="GetForumCategories"
            TypeName="Kawanoikioi.Models.AdminRepository"></asp:ObjectDataSource>
        <br />
        <asp:Label ID="DescriptionLabel" runat="server" Text="Description:"></asp:Label>
        &nbsp;&nbsp;&nbsp;
        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="ContentTextBox"
            ErrorMessage="A description for the forum must be specified."></asp:RequiredFieldValidator>
        <br />
        <asp:TextBox ID="ContentTextBox" runat="server" TextMode="MultiLine" Width="400px"
            Height="100px"></asp:TextBox>
        <ajaxToolkit:HtmlEditorExtender ID="ContentTextBox_HtmlEditorExtender" 
            runat="server" Enabled="True" TargetControlID="ContentTextBox">
        </ajaxToolkit:HtmlEditorExtender>
        <br />
        <asp:Label ID="ResultLabel" runat="server"></asp:Label>
        <br />
        <asp:Button ID="AddButton" runat="server" OnClick="AddButton_Click" Text="Add Forum" />
    </asp:Panel>
</asp:Content>
